set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)

include(${CMAKE_CURRENT_SOURCE_DIR}/scripts/cmake/dbg_sanitizers.cmake)
set(VCPKG_C_FLAGS ${MY_FLAGS})
set(VCPKG_CXX_FLAGS ${MY_FLAGS})
set(VCPKG_C_FLAGS_DEBUG ${MY_FLAGS_DEBUG})
set(VCPKG_CXX_FLAGS_DEBUG ${MY_FLAGS_DEBUG})

if(PORT STREQUAL "tensorflow-cc")
  set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()